import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import { type Config, defineConfig, globalIgnores } from 'eslint/config';
import tseslint from 'typescript-eslint';

// ESLint configuration, do not edit this file if you are not sure what you are doing.
// More details: https://eslint.org/docs/latest/use/configure/configuration-files;

const eslintConfig: Config[] = defineConfig([
  globalIgnores(['out/**', 'build/**', 'dist/**', 'coverage/**', 'node_modules/**']),

  js.configs.recommended,
  tseslint.configs.recommendedTypeChecked,
  prettier, // Disables conflicting rules between ESLint and Prettier.

  {
    files: ['**/*.ts'],
    languageOptions: {
      parserOptions: {
        project: './tsconfig.json',
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Only allow `import type` for types; enables better tree-shaking and clarity.
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],

      // Remove 'noUnusedLocals' and 'noUnusedParameters' from tsconfig.json to avoid duplicate errors.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],

      // Not error but warning, as there are some cases where 'any' is non-avoidable.
      '@typescript-eslint/no-explicit-any': 'warn',

      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
    },
  },
]);

export default eslintConfig;
