import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import { type Config, defineConfig, globalIgnores } from 'eslint/config';
import tseslint from 'typescript-eslint';

// ESLint configuration for the project, do not edit this file if you are not sure what you are doing.
// More details: https://eslint.org/docs/latest/use/configure/configuration-files

const eslintConfig: Config[] = defineConfig([
  // Ignore directories and files that are not relevant for linting.
  globalIgnores(['out/**', 'build/**', 'dist/**', 'coverage/**', 'node_modules/**']),

  js.configs.recommended, // Recommended ruleset for JavaScript, including common errors and best practices.
  tseslint.configs.recommendedTypeChecked, // Recommended ruleset for TypeScript.
  prettier, // Disables rules that might conflict with Prettier to avoid conflicts between the linter and formatter.

  {
    files: ['**/*.ts'],
    languageOptions: {
      parserOptions: {
        project: './tsconfig.json',
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Use only type imports for types, good practice, e.g. `import type { User } from './types';`
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],

      // Ignore unused variables that start with an underscore, a common convention for intentionally unused parameters or variables.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],

      // Only allow the `any` type when explicitly necessary, otherwise prefer more specific types for better type safety.
      '@typescript-eslint/no-explicit-any': 'warn',

      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': 'error',
    },
  },
]);

export default eslintConfig;
