# Justfile configuration file, do not edit this file if you are not sure what you are doing.
# More details about Justfile configuration: https://just.systems/man/en/quick-start.html;

quality:
    # Validates types, lints the codebase, and applies formatting.
    bun run typecheck && bun run lint && bun run format && bun run test
