import type { Config } from 'prettier';

// Prettier configuration, do not edit this file if you are not sure what you are doing.
// After making changes, run `bunx prettier --write .` to format all code in the project.
// More details about Prettier formatter: https://prettier.io/docs/en/configuration.html;

const prettierConfig: Config = {
  semi: true,
  singleQuote: true,
  quoteProps: 'consistent',
  printWidth: 120,
  tabWidth: 2,
  trailingComma: 'es5',
  arrowParens: 'always',

  // Import sorting via @trivago/prettier-plugin-sort-imports
  // More details: https://github.com/trivago/prettier-plugin-sort-imports

  importOrder: ['<THIRD_PARTY_MODULES>', '^@/', '^\\.{1,2}/'],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,

  plugins: ['@trivago/prettier-plugin-sort-imports'],
};

export default prettierConfig;
