import { tsconfigPathsPlugin } from 'esbuild-plugin-tsconfig-paths';
import { defineConfig } from 'tsup';

// Configuration for tsup to build the project, do not edit this file if you are not sure what you are doing.
// More details: https://tsup.egoist.dev/?ref=akashrajpurohit.com#typescript--javascript

const tsupConfig = defineConfig({
  format: ['esm'],
  target: 'esnext',

  dts: true, // Generates TypeScript declaration files
  clean: true, // Clean output directory before each build
  bundle: true, // Bundle all dependencies into the output files
  splitting: false, // Disable code splitting for single-file outputs

  esbuildPlugins: [tsconfigPathsPlugin()],
  entry: ['src/index.ts'],
});
export default tsupConfig;
