import type { Context, MiddlewareHandler } from 'hono';

import { isString } from '@/guard';

import { HONO_REQUEST_ID_HEADER } from './hono.constants';
import { honoErrors } from './hono.errors';
import type { HonoRequestIdMiddlewareOptions } from './hono.types';

/**
 * Resolves a request identifier from response metadata before its incoming header.
 * This ordering exposes identifiers generated by the request middleware downstream.
 */
export function getHonoRequestId(context: Context, header: string = HONO_REQUEST_ID_HEADER): string | undefined {
  const requestId = context.res.headers.get(header) ?? context.req.header(header);
  const normalizedRequestId = requestId?.trim();

  return normalizedRequestId || undefined;
}

/**
 * Creates middleware that preserves or generates one request correlation identifier.
 * The resolved value is returned on the response and remains available to Hono adapters.
 */
export function createRequestIdMiddleware(options: HonoRequestIdMiddlewareOptions = {}): MiddlewareHandler {
  const header = options.header ?? HONO_REQUEST_ID_HEADER;
  const createRequestId = options.createRequestId ?? (() => crypto.randomUUID());

  return async (context, next) => {
    const incomingRequestId = context.req.header(header)?.trim();
    const generatedRequestId = incomingRequestId ? undefined : createRequestId();
    const requestId = isString(generatedRequestId) ? generatedRequestId.trim() : incomingRequestId;

    const isInvalidRequestId = requestId === undefined || requestId.length === 0;
    if (isInvalidRequestId) throw honoErrors.invalidRequestId();

    context.header(header, requestId);
    await next();
    context.header(header, requestId);
  };
}

/**
 * Ready-to-use request identifier middleware backed by the shared default policy.
 * Applications may use the factory when a custom header or generator is required.
 */
export const requestIdMiddleware = createRequestIdMiddleware();
